[package]
name = "scoundrel-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
ron = "0.7"
serde = { version = "1", features = ["derive"] }

rand = "0.8.5"