[package]
name = "scoundrel-windowing"
version = "0.1.0"
edition = "2021"

[dependencies]
scoundrel-common = { path = "../scoundrel-common" }
glutin = "0.20"
gl = "0.14.0"
image = "0.23"
libc = "*"
crow = "0.7.2"
rand = "0.8.4"
static_assertions = "1.1.0"
