[package]
name = "scoundrel-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scoundrel-common = { path = "../scoundrel-common" }
rand = "0.8.5"
lazy_static = "1.4.0"